development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: a3_test
  username: act3
  password: klozz1
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: a3_prod
  username: act3
  password: klozz1
  pool: 5
