development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: a3_dev
  username: act3
  password: klozz1
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: a3_test
  username: act3
  password: klozz1
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: a3_prod
  username: act3
  password: klozz1
  pool: 5
